version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: crypto-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sns,cloudwatch
      - DEBUG=0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - crypto-network

networks:
  crypto-network:
    driver: bridge
